// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAP6Id9BcEjBqfYqxlRQQimvK--9l0Riw',
    appId: '1:1042959458689:web:c2a8b9badb73021ac2c880',
    messagingSenderId: '1042959458689',
    projectId: 'dwm-atividade2',
    authDomain: 'dwm-atividade2.firebaseapp.com',
    databaseURL: 'https://dwm-atividade2-default-rtdb.firebaseio.com',
    storageBucket: 'dwm-atividade2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Fzu8bYtjv6lDIZjWdef6GsxRQxxjyII',
    appId: '1:1042959458689:android:c2749404f5e51bc1c2c880',
    messagingSenderId: '1042959458689',
    projectId: 'dwm-atividade2',
    databaseURL: 'https://dwm-atividade2-default-rtdb.firebaseio.com',
    storageBucket: 'dwm-atividade2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC-eu1TxI7oTsMHBWDKG5wNbC61yaxnh8',
    appId: '1:1042959458689:ios:67f8001b16919b98c2c880',
    messagingSenderId: '1042959458689',
    projectId: 'dwm-atividade2',
    databaseURL: 'https://dwm-atividade2-default-rtdb.firebaseio.com',
    storageBucket: 'dwm-atividade2.appspot.com',
    iosClientId: '1042959458689-hkl148trhjkj93elhmu0u3i2mjblccou.apps.googleusercontent.com',
    iosBundleId: 'com.example.dwm2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC-eu1TxI7oTsMHBWDKG5wNbC61yaxnh8',
    appId: '1:1042959458689:ios:67f8001b16919b98c2c880',
    messagingSenderId: '1042959458689',
    projectId: 'dwm-atividade2',
    databaseURL: 'https://dwm-atividade2-default-rtdb.firebaseio.com',
    storageBucket: 'dwm-atividade2.appspot.com',
    iosClientId: '1042959458689-hkl148trhjkj93elhmu0u3i2mjblccou.apps.googleusercontent.com',
    iosBundleId: 'com.example.dwm2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAP6Id9BcEjBqfYqxlRQQimvK--9l0Riw',
    appId: '1:1042959458689:web:f18a9038a7de1dc4c2c880',
    messagingSenderId: '1042959458689',
    projectId: 'dwm-atividade2',
    authDomain: 'dwm-atividade2.firebaseapp.com',
    databaseURL: 'https://dwm-atividade2-default-rtdb.firebaseio.com',
    storageBucket: 'dwm-atividade2.appspot.com',
  );
}
